version: 16
jobs:
- name: Continous delivery
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: install dependencies and run tests
    runInContainer: true
    image: python:latest
    interpreter: !DefaultInterpreter
      commands:
      - pip install -r requirements.txt
      - pytest src/test.py -v
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build and push docker image
    tags: localhost:5000/custom-image:@commit_hash@ localhost:5000/custom-image:latest
    publish: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  jobExecutor: server-docker
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
