---
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    ports:
      - 127.0.0.1:3000:3000

  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000

  onedev:
    image: 1dev/server
    volumes:
      - ./volumes/onedev_data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:6610:6610
      - 127.0.0.1:6611:6611