---

networks:
  internal:
    external: false

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal

  grafana:
    image: grafana/grafana-oss
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal

  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - internal

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registru-ui
    ports:
      - 127.0.0.1:8080:80
    environment:
       ENV_DOCKER_REGISTRY_HOST: docker-registry
       ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      - internal

  onedev:
    image: 1dev/server
    volumes:
      - ./volumes/onedev_data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:6610:6610
      - 127.0.0.1:6611:6611
    networks:
      - internal